#config_version=5
mode:
  start_events: sw_threes_active, game_started
  stop_events: sw_third_base_rollover_active
  priority: 100

show_player:
  mode_threes_lit_started:
    threes_on: play
  mode_threes_lit_stopped:
    threes_off: play