#config_version=5
mode:
  start_events: ball_starting
  priority: 100
  
slide_player:
  mode_score_display_started:
    base_player_dmd_slide:
      target: dmd
    base_player_window_slide:
      target: window
    
slides:
  base_player_dmd_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        color: f87217
        min_digits: 2
        style: dmd_big
        x: center
        y: top - 5
        anchor_x: center
        anchor_y: top
      - type: text
        text: PLAYER (number)
        color: f87217
        y: 0
        x: 0
        style: dmd_small
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        color: f87217
        y: 0
        x: right
        anchor_x: right
        anchor_y: bottom
        style: dmd_small
  base_player_window_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        color: f87217
        min_digits: 2
        style: dmd_big
        x: center
        y: top - 5
        anchor_x: center
        anchor_y: top
      - type: text
        color: f87217
        text: PLAYER (number)
        y: 0
        x: 0
        style: dmd_small
        anchor_x: left
        anchor_y: bottom
      - type: text
        color: f87217
        text: BALL (ball)
        y: 0
        x: right
        anchor_x: right
        anchor_y: bottom
        style: dmd_small