#config_version=5
mode:
  start_events: ball_starting
  priority: 100
  
slide_player:
  mode_score_display_started:
    base_player_dmd_slide:
      target: dmd
    
slides:
  base_player_dmd_slide:
    - type: text
      text: (score)
      style: big
      number_grouping: true
      color: f87217
      min_digits: 2
      x: center
      y: top - 5
      anchor_x: center
      anchor_y: top
    - type: text
      text: PLAYER (number)
      style: small
      color: f87217
      y: 0
      x: 0
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      style: small
      color: f87217
      y: 0
      x: right
      anchor_x: right
      anchor_y: bottom