#config_version=5
mode:
  start_events: sw_twos_active, game_started
  stop_events: sw_second_base_rollover_active
  priority: 100

show_player:
  mode_twos_lit_started:
    twos_on: play
  mode_twos_lit_stopped:
    twos_off: play