#config_version=5

ball_devices:
  bd_drain:
    ball_switches: s_drain
    entrance_count_delay: 300ms
    eject_coil: c_drain_eject
    player_controlled_eject_event: s_right_flipper_active
    confirm_eject_type: switch
    confirm_eject_switch: s_drain
    eject_timeouts: 3s
    tags: drain, home, trough

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slightshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  left_pop_bumper:
    coil: c_left_pop_bumper
    switch: s_left_pop_bumper
  right_pop_bumper:
    coil: c_right_pop_bumper
    switch: s_right_pop_bumper
  center_pop_bumper:
    coil: c_center_pop_bumper
    switch: s_center_pop_bumper

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper