#config_version=5

hardware:
  rgb_dmd: smartmatrix

smartmatrix:
  smartmatrix_1:
    port: "/dev/ttyUSB4"
    baud: 3000000
    old_cookie: false

displays:
  dmd:
    width: 128
    height: 32
    default: true
    
rgb_dmds:
  smartmatrix_1:
    hardware_brightness: 0.3
    fps: 24
    source_display: dmd  