#config_version=5

switches:
  s_drain:
    number: 0-8
    tags: drain, 
  s_home_run_lanes:
    number: 0-9
    tags: playfield_active
  s_single_lanes:
    number: 0-10
    tags: playfield_active
  s_first_base:
    number: 0-11
    tags: playfield_active, first_base_rollover_active
  s_second_base:
    number: 0-12
    tags: playfield_active, second_base_rollover_active
  s_third_base:
    number: 0-13
    tags: playfield_active, third_base_rollover_active
  s_home_base:
    number: 0-14
    tags: playfield_active, home_base_rollover_active
  s_double_lanes:
    number: 0-15
    tags: playfield_active
  s_right_vt_inplay:
    number: 0-16
    tags: playfield_active, rvt_inplay
    events_when_activated: collect_varitarget_r
  s_right_vt_100:
    number: 0-24
    tags: playfield_active
  s_right_vt_200:
    number: 0-25
    tags: playfield_active
  s_right_vt_300:
    number: 0-26
    tags: playfield_active
  s_right_vt_500:
    number: 0-27
    tags: playfield_active
  s_right_slingshot:
    number: 0-18
  s_left_slingshot:
    number: 0-19
  s_left_vt_inplay:
    number: 0-17
    tags: playfield_active, lvt_inplay
    events_when_activated: collect_varitarget_l
  s_left_vt_100:
    number: 0-28
    tags: playfield_active
  s_left_vt_200:
    number: 0-29
    tags: playfield_active
  s_left_vt_300:
    number: 0-30
    tags: playfield_active
  s_left_vt_500:
    number: 0-31
    tags: playfield_active
  s_right_pop_bumper:
    number: 0-22
  s_left_pop_bumper:
    number: 0-23
  s_center_pop_bumper:
    number: 0-7
  s_lower_target_1:
    number: 0-20
    tags: playfield_active, ones_active
  s_lower_target_3:
    number: 0-21
    tags: playfield_active, threes_active
  s_left_target_3:
    number: 0-0
    tags: playfield_active, threes_active
  s_left_target_2:
    number: 0-1
    tags: playfield_active, twos_active
  s_left_target_1:
    number: 0-2
    tags: playfield_active, ones_active
  s_right_target_1:
    number: 0-3
    tags: playfield_active, ones_active
  s_right_target_2:
    number: 0-4
    tags: playfield_active, twos_active
  s_right_target_3:
    number: 0-5
    tags: playfield_active, threes_active
  s_bumpers:
    number: 1-0
    tags: playfield_active
  s_triple_lanes:
    number: 0-6
    tags: playfield_active
  s_start:
    number: 1-5
    tags: start
    label: "Start"
  s_left_flipper:
    number: 1-6
    tags: left_flipper, playfield_active
  s_right_flipper:
    number: 1-7
    tags: right_flipper, playfield_active